use bamazon_1;
insert into products(product_name,department_name,price,stock_quantity)values("Persian Heriz", "Rugs", 999, 900);
insert into products(product_name,department_name,price,stock_quantity)values("Persian Tabriz", "Rugs", 950.00, 890);
insert into products(product_name,department_name,price,stock_quantity)values("Persian Qhom", "Rugs", 600.00, 719);
insert into products(product_name,department_name,price,stock_quantity)values("Persian Taba-Tabriz", "Rugs", 900, 920);
insert into products(product_name,department_name,price,stock_quantity)values("Persian Mashad ", "Rugs", 990, 850);
insert into products(product_name,department_name,price,stock_quantity)values("Persian Sarouk", "Rugs", 950, 711);
insert into products(product_name,department_name,price,stock_quantity)values("Persian Farahan", "Rugs", 920, 825);
insert into products(product_name,department_name,price,stock_quantity)values("Persian Serapi", "Rugs", 958, 948);
insert into products(product_name,department_name,price,stock_quantity)values("Persian Gharajeh", "Rugs", 975, 950);
insert into products(product_name,department_name,price,stock_quantity)values("Persian Haj-Alli", "Rugs", 980, 825);
insert into products(product_name,department_name,price,stock_quantity)values("Persian Bidjar", "Rugs", 911, 111);